/**
 * +page.ts — SvelteKit Load Function for the Product Detail page.
 *
 * SVELTEKIT LOAD FUNCTIONS
 * =========================
 * Every +page.svelte can have a sibling +page.ts (or +page.server.ts)
 * that exports a `load` function. This function runs BEFORE the page
 * renders, providing data that the page component receives via $props().
 *
 * Load functions are called:
 * - On the server during SSR (or SSG at build time)
 * - On the client during client-side navigation
 *
 * They receive a context object with:
 * - params: URL parameters from dynamic route segments
 * - url: the full URL object
 * - fetch: a special fetch that works on both server and client
 * - depends: for fine-grained invalidation
 *
 * DYNAMIC ROUTE PARAMETERS
 * =========================
 * The [id] in the folder name (src/routes/products/[id]) creates a
 * dynamic route parameter. When a user visits /products/prod_001,
 * params.id will be "prod_001".
 *
 * Square brackets in folder names = dynamic segments:
 * - [id] -> params.id (required)
 * - [[optional]] -> params.optional (optional)
 * - [...rest] -> params.rest (catch-all)
 */

/**
 * Load function for the product detail page.
 *
 * We extract the `id` param and return it as page data.
 * The actual product lookup happens in the +page.svelte component
 * using the mock data helper. In a real app, you would fetch the
 * product from an API here:
 *
 *   const product = await fetch(`/api/products/${params.id}`);
 *
 * The return value becomes available in the page component as:
 *   let { data } = $props();  // data.id is the product ID
 *
 * NOTE: The `$types` module (e.g., `import type { PageLoad } from './$types'`)
 * is auto-generated by SvelteKit when you run `dev` or `build`. If you see
 * a "cannot find module" error, run `npm run dev` once to generate the types.
 * Here we use inline typing for simplicity.
 */
export function load({ params }: { params: { id: string } }) {
  return {
    id: params.id
  };
}
